      SUBROUTINE GEG(MAXLMD, NL3, ZETA3, AC, RLEAG0, GEGIN2)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"
      DIMENSION RLEAG0(*), GEGIN2(*)
      DIMENSION BESI(0:100), BESK(0:100)


      DO 5 I=1, LEA11
       R2 = RLEAG0(I)

       RM = ZETA3*DMIN1(R2, AC)
       RP = ZETA3*DMAX1(R2, AC)

       FRAC1 = RM/RP
       FRAC2 = FRAC1*FRAC1

       CALL BESSI(-NL3, MAXLMD+NL3, RM, BESI)
       CALL BESSK(MAXLMD+NL3, RP, BESK)

       CSTE = (0.5D0*RP/ZETA3)**NL3

       DO 5 LMD=0, MAXLMD

	POWR = 1.D0
	SUMP = BESPRO(RM, NL3, LMD, BESI, BESK, 0, POWR, FRAC2)

	POWR = FRAC1
	SUMN = BESPRO(RM, NL3, LMD, BESI, BESK, 1, POWR, FRAC2)

	INDEX = LMD*LEA11 + I
	GEGIN2(INDEX) = CSTE * (SUMP-SUMN)

 5    CONTINUE


      RETURN
      END
