C.... THESE ARE SOME GAUNT COEFFICIENTS

      SUBROUTINE HUSES1(INDEX, L1,M1, L2,M2, ARGNTX)
      IMPLICIT REAL*8 (A-H, O-Z)
      DIMENSION ARGNTX(*)

C     IL FAUT CONNAITRE LA DIMENSION DE ARGNTX AFIN DE POUVOIR INITIALISER
C     PROPREMENT


      CALL RAZ1(ARGNTX, 1,LMDMAX)


      DO 5 L=0, LMDMAX
      DO 5 M=-L, L

      DO 5 LP2=0, L2
      DO 5 MP2=MAX(-LP2, -L2+LP2+M2), MIN(LP2, L2-LP2+M2)

       LP12X = L1+LP2
       LP12M = 2*((LP12X + MAX0(IABS(L1-LP12), IABS(MP2-M1))+1)/2)-LP12X

       LP12I = IABS(L1-LP2)

      DO 5 LP12=LP12M, LP12X, 2

       LMDX1 = L+LP12
       LMDM1 = IABS(L-LP12)
       NTERS = (LMDX1 - LMDM1)/2 + 1

       INDEX = INDEX + (LP12M - LP12I)/2 * NTERS + 1

       CALL GAUNT(LP12,MP2-M1,L,M, LMDM,LMDX,M12, NGAUNT, ARGNTX(INDEX))

 5    CONTINUE

      RETURN
      END
