      SUBROUTINE TETRAC(NEPSIL, NTORB,NSUM, LM123,
     $                    NORB1,NORB2,NORB3,NORB4,
     $                    NLMA,NLMB,NLMC,NLMD,
     $                    ZETAA,ZETAB,ZETAC,ZETAD,ZETAMY,
     $        AB,THETAB,PHIAB, AC,THETAC,PHIAC, AD,THETAD,PHIAD, FATIMA)
      IMPLICIT REAL*8 (A-H, O-Z)
      COMPLEX*16 OUIZA
      INCLUDE "../lib95/SIZE.INCL"
      INCLUDE "../lib95/CONST.INCL"

      DIMENSION ARGNTX(100 000), ARGNTY(100 000)
      DIMENSION OUIZA(20,20,20,20)

      DIMENSION NLMA(*),NLMB(*),NLMC(*),NLMD(*),
     $          ZETAA(*),ZETAB(*),ZETAC(*),ZETAD(*), FATIMA(*)

      DIMENSION YLMAB(0:((LDEV+1)*(LDEV+2))/2),
     $           YLMAC(0:((LDEV+1)*(LDEV+2))/2),
     $           YLMAD(0:((LDEV+1)*(LDEV+2))/2), RADAR(1 117 252)

      DIMENSION ARGNT1((L2MAX+1)*(L2MAX+1)),
     $          ARGNT2((L1MAX+1)*(L2MAX+1)*(2*L2MAX+1)),
     $          ARGNT3((L3MAX+1)*(L3MAX+1)),
     $          ARGNT4((L4MAX+1)*(L4MAX+1)),
     $          ARGNT5((L3MAX+1)**2*(L4MAX+1)**2*(L3MAX+L4MAX+1))


      COMMON/FACT0/FACT(0:30)
      COMMON/DFACT/DFAC(0:20)
      COMMON/GLAE0/RLEAG0(LMHERM), ISP
      COMMON/XROOTS/ROOTS(LEA11*LEA12), ISQ
      COMMON/COMG00/GEGIN0(LMHERM*LMHERM*(LMDMAX+L1MAX+L2MAX+1))
      COMMON/COMG01/GEGIN1(NORBM/2*(LDEV+1)*LEA11)
      COMMON/COMG02/GEGIN2((2*LDEV+1)*LEA11)
      COMMON/COMG03/GEGIN3(0:(LMDMAX+1)*(LMDMAX+1)*LEA11)
      COMMON/COMV00/VL(20*20*(LDEV+1)*LEA12)
      COMMON/INTEGN/NINT

      RMIN = DMIN1(AC, AD)
      RMIN1 = DMIN1(AD, AB)
      RMAX = DMAX1(AC, AD)
c      RMAX1 = DMAX1(AD, AB)
c      IF(RMIN.GT.3.0d0.OR.RMIN1.GT.3.0d0)GO TO 100
cd      IF(RMAX.GT.3.5d0)GO TO 100
cc      IF(RMIN.GT.2.5d0)GO TO 100

C.... COMPUTATION OF THE REQUIRED SPHERICAL HARMONICS

      CALL YLMV2(THETAB, THETAC, THETAD, YLMAB, YLMAC, YLMAD)

C.... COLLECTING THE ROOTS OF THE DOUBLE INTEGRAL (I.E. OVER R1 AND R2)
C.... THERE WILL BE THREE-SPHERES WHOSE RADIUS ARE RMIN, RMED, RMAX.


      CALL DUMMY4(ZETAMY, RMIN, RMAX, AB)

C.... COMPUTATION AND STORAGE OF THE GEGENBAUER COEFFICIENTS FOR THE
C.... THE COMPUTATION OF THE T.C.C.D.P.

C.... COMPUTATION OF THE GAUSS-LAGUERRE ROOTS FOR THE INNERMOST INTEGRAL (R1)

cc      cpin = mclock()

      INDEX = 1

      DO 5 NAT2=1, NORB2
       JST   = 5*(NAT2-1)
       NO2   = NLMB(JST+2)
       N2    = NLMB(JST+3)
       L2    = NLMB(JST+4)
       M2    = NLMB(JST+5)
       ZETA2 = ZETAB(NAT2)

cc       CPI = MCLOCK()
       LMDL12 = LMDMAX+LM123+L2+1
       CALL GEGEN9(LMDL12, N2-L2, ZETA2, AB, RLEAG0, ROOTS, GEGIN0)
cc       CPF = MCLOCK()
      DO 5 NAT1=1, NORB1
       IST   = 5*(NAT1-1)
       NO1   = NLMA(IST+2)
       N1    = NLMA(IST+3)
       L1    = NLMA(IST+4)
       M1    = NLMA(IST+5)
       ZETA1 = ZETAA(NAT1)

       CALL TCCDP5(INDEX, LM123, N1,L1, N2,L2, ZETA1,ZETA2,
     $                                         AB,RMIN,RMAX, RLEAG0, VL)
 5    CONTINUE

cc      etime = 1.d-2*(mclock() - cpin)/dble(norb1*norb2)

cc      WRITE(*, *)'TEMPS POUR TCCDP5 ', NORB1*NORB2, ETIME


C.... COMPUTATION OF THE GEGENBAUERS' COEFFICIENTS FOR THE FOURTH STO ONCE AND FO ALL

      LM4D = LMDMAX
      CALL GEGDER(LM4D, NORB4,NLMD,ZETAD,AD, LEA11, RLEAG0, GEGIN1)

C.... COMPUTATION OF THE FOUR-CENTER INTEGRAL

       DO 10 NAT3=1, NORB3
       KST   = 5*(NAT3-1)
       NO3   = NLMC(KST+2)
       N3    = NLMC(KST+3)
       L3    = NLMC(KST+4)
       M3    = NLMC(KST+5)
       ZETA3 = ZETAC(NAT3)

C.... COMPUTATION OF THE THIRD SERIES OF GEGENBAUERS' COEFFICIENTS

       LM3D = 2*LMDMAX+LM123+L3

       CALL GEG(LM3D, N3-L3, ZETA3, AC, RLEAG0, GEGIN2)

      DO 10 NAT4=1, NORB4
       LST   = 5*(NAT4-1)
       NO4   = NLMD(LST+2)
       N4    = NLMD(LST+3)
       L4    = NLMD(LST+4)
       M4    = NLMD(LST+5)
       ZETA4 = ZETAD(NAT4)

       CALL HUSED(DFAC, L3,M3, L4,M4, AC,YLMAC, AD,YLMAD,
     $                                           ARGNT3, ARGNT4, ARGNT5)
C      CALL HUSES2(L3,M3,YLMAC, L4,M4,YLMAD, ARGNT3,ARGNT4,ARGNT5)
C
C.... EXPANSION OF THE PRODUCT OF TWO STO IN TERMS OF SPHERICAL HARMONICS
C
C     CP1 = MCLOCK()
C
C     CALL STOPAT(NAT4, LM4D,GEGIN2, LM3D,GEGIN1, PHIAC,YLMAC,
C    $                                                      PHIAD,YLMAD)
C
C     WRITE(*, *)'EXITING THE STOPAT LINK ', 1.D-2*(MCLOCK() - CP1)

      INDVL0 = 1

c     # HERE! ury
      DO 10 NAT2=1, NORB2
       JST   = 5*(NAT2-1)
       NO2   = NLMB(JST+2)
       N2    = NLMB(JST+3)
       L2    = NLMB(JST+4)
       M2    = NLMB(JST+5)
       ZETA2 = ZETAB(NAT2)

      DO 10 NAT1=1, NORB1
       IST   = 5*(NAT1-1)
       NO1   = NLMA(IST+2)
       N1    = NLMA(IST+3)
       L1    = NLMA(IST+4)
       M1    = NLMA(IST+5)
       ZETA1 = ZETAA(NAT1)

       CALL RADFC(NAT4, L1,L2,L3,L4, INDVL0, LM4D,
     $                                        RMIN, RMAX, ZETAMY, RADAR)

       CALL FUSED(DFAC, L1,M1, L2,M2, AB,YLMAB, ARGNT1, ARGNT2)

c       WRITE(*, *)'ENTERING FCINTS '
c       CPIN = MCLOCK()

       CALL FCINTS(NEPSIL, N1,L1,M1, N2,L2,M2, N3,L3,M3, N4,L4,M4,
     $                  ZETA1,ZETA2,ZETA3,ZETA4,
     $                  AB,PHIAB,YLMAB, AC,PHIAC,YLMAC, AD,PHIAD,YLMAD,
     $                  ARGNT1, ARGNT2, ARGNT3, ARGNT4, ARGNT5,
     $                  RADAR, TETRAR, TETRAI)

      OUIZA(NAT1,NAT2,NAT3,NAT4) = DCMPLX(TETRAR, TETRAI)

      NINT = NINT + 1

c      WRITE(*, 1)NO1,NO2,NO3,NO4, TETRAR, TETRAI

c      CPOUT = MCLOCK()
c      WRITE(*,*)'EXITING FCINTS ', 1.D-2*(CPOUT-CPIN)

 10   CONTINUE

c 1    FORMAT(4Z2, 2X, D16.10, D16.10)

      CALL REAL07(NORB1,NORB2,NORB3,NORB4, NLMA,NLMB,NLMC,NLMD,
     $                                       NTORB, NSUM, OUIZA, FATIMA)
 100  CONTINUE
      RETURN
      END
