CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS ROUTINE RETURNS THE SPHERICAL HARMONICS DEPENDING ON THE AB  *C
C* VECTOR PARAMETERS.                                                *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE YLMV2(THETAB, THETAC, THETAD, YLMAB, YLMAC, YLMAD)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"
      DIMENSION YLMAB(0:*), YLMAC(0:*), YLMAD(0:*), YLMO(0:LDEV)


      DO 5 MU=0, LDEV
       CALL SPHRM(LDEV, MU, DCOS(THETAB), YLMO)
       NAB = (MU*(MU+1))/2 + MU
      DO 5 LMD=MU, LDEV
       YLMAB(NAB) = YLMO(LMD)
       NAB        = NAB + LMD + 1
 5    CONTINUE

      DO 10 MU=0, LDEV
       CALL SPHRM(LDEV, MU, DCOS(THETAC), YLMO)
       NAC = (MU*(MU+1))/2 + MU
      DO 10 LMD=MU, LDEV
       YLMAC(NAC) = YLMO(LMD)
       NAC        = NAC + LMD + 1
 10   CONTINUE

      DO 15 MU=0, LDEV
       CALL SPHRM(LDEV, MU, DCOS(THETAD), YLMO)
       NAD = (MU*(MU+1))/2 + MU
      DO 15 LMD=MU, LDEV
       YLMAD(NAD) = YLMO(LMD)
       NAD        = NAD + LMD + 1
 15   CONTINUE

      RETURN
      END
