CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS SUBROUTINE RETURNS A SET OF TWO-CENTER HYBRID INTEGRALS OVER *C
C* A SLATER ORBITAL BASIS SET USING A TWO-RANGE ON-CENTER EXPANSION  *C
C* METHOD.                                                           *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE HYBRID(NEPSIL, NTORB,NSUM, LM123, NORB1,NORB2,
     $                  NLMA,NLMB, ZETAA,ZETAB, AB,THETAB,PHIAB, FATIMA)
      IMPLICIT REAL*8 (A-H, O-Z)
      COMPLEX*16 OUIZA
      INCLUDE "../lib95/SIZE.INCL"
      INCLUDE "../lib95/CONST.INCL"

      DIMENSION NLMA(*), NLMB(*), ZETAA(*), ZETAB(*), FATIMA(*)

      DIMENSION YLMAB(0:((LDEV+1)*(LDEV+2))/2),
     $      RADAR((L1MAX+1)*(L2MAX+1)*(L4MAX+1)*(L1MAX+L2MAX+1)),
     $      ARGNT1((L4MAX+1)*(L4MAX+1)), ARGNT2((L4MAX+1)**3),
     $      ARGNT3(L1MAX+1), ARGNT4((L1MAX+L2MAX+1)), INX(7)

      DIMENSION OUIZA(20,20,20,20)


      COMMON/FACT0/FACT(0:30)
      COMMON/DFACT/DFAC(0:100)
      COMMON/GLE01/RLEG01(L001+L002+L003)
      COMMON/GLE02/RLEG02(L004+L005+L006)
      COMMON/BESS0/BESF01(2*LTOT6)
      COMMON/X4POW/X4NL(10*LTOT6)
      COMMON/GLAE0/RLEAG0(LMHERM), ISP
      COMMON/COMG00/GEGIN0(LMHERM*LMHERM*(LMDMAX+L1MAX+L2MAX+1))
      COMMON/COMV00/VL((NORBM*(NORBM+1))/2*(L1MAX+L2MAX+1)*LEA02)
      COMMON/INTEGN/NINT

c      if(ab.gt.4)then
c      hybr=1/ab
c      goto 100
c      endif


C.... CASE OF LINEAR SYSTEMS

       REMAIN = DABS(DMOD(THETAB, PI))

C.... COMPUTATION OF THE REQUIRED SPHERICAL HARMONICS

      CALL YLMV0(THETAB, YLMAB)

C.... COLLECTING THE ROOTS OF THE GAUSS QUADRATURES FOR COMPUTING THE RADIAL INTEGRAL

      CALL DUMMY0(AB, LEG03)
c      CALL DUMMY0(AB, 8)

C.... COMPUTATION OF SOME VALUES OF THE ONE-CENTER CHARGE DISTRIBUTION
C.... POTENTIAL

      CALL OCCDP(L1MAX+L2MAX, NORB1, NLMA,ZETAA, RLEAG0,LEG03,LEA02, VL)
c      CALL OCCDP(L1MAX+L2MAX, NORB1, NLMA,ZETAA, RLEAG0,8,LEA02, VL)

C.... COMBINATION OF THE GIVEN SET OF SLATER ORBITALS

      DO 5 NAT4=1, NORB2
       LST   = 5*(NAT4-1)
       NO4   = NLMB(LST+2)
       N4    = NLMB(LST+3)
       L4    = NLMB(LST+4)
       M4    = NLMB(LST+5)
       ZETA4 = ZETAB(NAT4)

C.... COMPUTATION OF THE COEFFICIENTS INVOLVED IN THE GEGENBAUER ADDITION THEROREM

       LMDL12 = LM123+LM123+LM123+L4+1
       CALL GEGEN2(LMDL12, N4-L4, ZETA4, AB, RLEG01, RLEG02, RLEAG0,
     $                                             BESF01, X4NL, GEGIN0)

      DO 5 NAT3=1, NORB1
       KST   = 5*(NAT3-1)
       NO3   = NLMA(KST+2)
       N3    = NLMA(KST+3)
       L3    = NLMA(KST+4)
       M3    = NLMA(KST+5)
       ZETA3 = ZETAA(NAT3)

C.... COMPUTATION OF THE GEGENBAUER COEFFIENTS

       CALL GEGOX (LMDL12, N4-L4, ZETA3,ZETA4, AB, RLEG01, RLEG02,
     $                                             BESF01, X4NL, GEGIN0)

C.... COMPUTATION OF THE COEFFICIENTS INVOLVED IN THE SOLID SPHERICAL HAMONICS

       CALL FUSED(DFAC, L3,M3, L4,M4, AB, YLMAB, ARGNT1, ARGNT2)

       INDEX = 0

      DO 5 NAT2=1, NORB1
       JST   = 5*(NAT2-1)
       NO2   = NLMA(JST+2)
       N2    = NLMA(JST+3)
       L2    = NLMA(JST+4)
       M2    = NLMA(JST+5)
       ZETA2 = ZETAA(NAT2)

      DO 5 NAT1=NAT2, NORB1
       IST   = 5*(NAT1-1)
       NO1   = NLMA(IST+2)
       N1    = NLMA(IST+3)
       L1    = NLMA(IST+4)
       M1    = NLMA(IST+5)
       ZETA1 = ZETAA(NAT1)

C.... COMPUTATION OF SOME VALUES OF THE ONE-CENTER CHARGE DISTRIBUTION POTENTIAL

       N12    = N1+N2
       L12    = L1+L2
       ZETA12 = ZETA1+ZETA2
       CALL OCCDP1(L1MAX+L2MAX, INDEX, N12, L12, ZETA12, RLEAG0,LEG03,
     $                                                        LEA02, VL)

C.... COMPUTATION OF THE RADIAL INTEGRAL

       CALL RHYB(INDEX, L1,L2, N3,L3, N4,L4, ZETA3,ZETA4, AB, RADAR)
       INDEX = INDEX + 1

C.... COMPUTATION OF THE HYBRID INTEGRAL FOR THE SELECTED PARAMETERS

       CALL HYBRD(N1,L1,M1, N2,L2,M2, N3,L3,M3, N4,L4,M4, ZETA1,
     $    ZETA2,ZETA3,ZETA4, AB,YLMAB,PHIAB, ARGNT1,ARGNT2, RADAR, HYB)

C.... GLOBAL AZIMUTHAL ANGLE

       ANGLE  = ((M4-M3)+(M2-M1))*PHIAB
       COSINE = DCOS(ANGLE)
       SINE   = DSIN(ANGLE)

       HYBR   = COSINE * HYB
       HYBI   = SINE   * HYB

c      WRITE(*, 1) NO1,NO2,NO3,NO4, HYBR,  HYBI
c      WRITE(*, 2) N1,L1,M1, ZETA1
c      WRITE(*, 2) N2,L2,M2, ZETA2
c      WRITE(*, 2) N3,L3,M3, ZETA3
c      WRITE(*, 2) N4,L4,M4, ZETA4
c      write(*, 3) HYBR, HYBI
c      write(*,*)

       OUIZA(NAT1, NAT2, NAT3, NAT4) = DCMPLX(HYBR,  HYBI)

       NINT = NINT + 1

 5    CONTINUE

 1    FORMAT(4(I2, 1X), 2(D20.14, 1X))
 2    FORMAT(3(I2, 1X), F7.5)
 3    FORMAT(2(D20.14, 1X))

C.... SYMMETRIZATION OF THE INTEGRALS
C.... COMPUTATION OF THE INTEGRALS <I,J, L,K> AND <J,I, K,L>

      CALL SYMM03(NORB1,NORB2, NLMA,NLMB, OUIZA)
      CALL REAL03(NORB1,NORB2, NLMA,NLMB,
     $     NTORB, NSUM, OUIZA, FATIMA)
  100 continue
      RETURN
      END
