CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS ROUTINE RETURNS THE RADIAL INTEGRAL OCCURING IN THE HYBRID   *C
C* INTEGRALS. THESE VALUES ARE STORED IN THE ONE-DIMENSIONAL ARRAY   *C
C* RADAR.                                                            *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE RHYB(INDIC, L1,L2, N3,L3, N4,L4, ZETA3,ZETA4, AB,RADAR)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"
      DIMENSION RADAR(*)
      COMMON/STOP02/ZETA3P, N3P, L12, L, LP4, LMD, ISTR, NSTRT
      COMMON/COMG00/GEGIN0(LMHERM*LMHERM*(LMDMAX+L1MAX+L2MAX+1))
      COMMON/COMV00/VL((NORBM*(NORBM+1))/2*(L1MAX+L2MAX+1)*LEA02)
      EXTERNAL RAD03

C.... PASSAGE TO COMMON

      ZETA3P = ZETA3
      N3P    = N3
      L12    = L1+L2
      NSTRT  = INDIC*LEA02*(L1MAX+L2MAX+1)

      INDEX = 1

      DO 5 L=IABS(L1-L2), L1+L2, 2
      DO 5 LP4=0, L4
      DO 5 LP34=IABS(L3-LP4), L3+LP4, 2
      DO 5 LMD=IABS(L-LP34), L+LP34, 2
       ISTR         = 0
       XINT1        = DGLNQ(RAD03, 0.D0, AB, LEG03)
       ISTR         = ISTR + LEG03
       XINT2        = DGLGQ(RAD03, AB, ZETA3+ZETA4, LAG02)
       RADAR(INDEX) = XINT1 + XINT2
C      WRITE(*, *)INDEX, RADAR(INDEX)
       INDEX        = INDEX + 1
 5    CONTINUE


      RETURN
      END



      SUBROUTINE RAD03(T, Y, N)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"
      DIMENSION T(*), Y(*)
      COMMON/STOP02/ZETA3, N3, L12, L, LP4, LMD, ISTR, NSTRT
      COMMON/COMG00/GEGIN0(LMHERM*LMHERM*(LMDMAX+L1MAX+L2MAX+1))
      COMMON/COMV00/VL((NORBM*(NORBM+1))/2*(L1MAX+L2MAX+1)*LEA02)


      INDO = LMD*LEA02 + ISTR

      DO 5 I=1, N
       INDX = NSTRT + (ISTR+I-1)*(L12+1) + L+1
       R2   = T(I)
       Y(I) = 1.D0/DSQRT(R2) * R2**(N3+LP4+1) * DEXP(-ZETA3*R2) *
     $                                         VL(INDX) * GEGIN0(INDO+I)
C      WRITE(*, *)INDX, VL(INDX)

 5    CONTINUE

      RETURN
      END
