CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS ROUTINE COMPUTES THE CHARGE DENSITY FOR A GIVEN (INCH ALLAH) *C
C* DENSITY AND OVERLAP MATRICES, WHERE NATO REPRESENTS THE TOTAL     *C
C* NUMBER OF ATOMIC ORBITALS USED TO DESCRIBE THE SYSTEM.            *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE CHDENS(NATOM, NATO,NORBAT,NUMAT,SOVL,PMN,EDENS,CHDNS)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"

      DIMENSION NORBAT(*), SOVL(N_ORB,N_ORB), PMN(N_ORB,N_ORB), EDENS(*)
      DIMENSION NUMAT(*), CHDNS(N_ORB,N_ORB)


C.... COMPUTATION OF THE 2-DIMENSIONAL ARRAY : CHDENS = P S
      DO 4 I = 1, NATO
      DO 4 J = 1, NATO
      DO 4 K = 1,NATO
      CHDNS(I,J)=CHDNS(I,J)+PMN(K,I)*SOVL(K,J)
 4    CONTINUE
c      

C     A=PMN
C     LDA=N_ORB
C     TRANSA='N'
C     B=SOVL
C     LDB=N_ORB
C     C=CHDNS
C     LDC=N_ORB

c     CALL DGEMM('N','N', NATO,NATO,NATO,PMN,NATO, SOVL,
c    $ NATO,0,CHDNS,NATO)
c      CALL DGEMUL(PMN,N_ORB, 'N', SOVL,N_ORB, 'N', CHDNS,N_ORB,
c     $                                                  NATO,NATO)

C.... WRITE(*, *)'ELECTRON CHARGE MATRIX '
C.... CALL MATOUT(CHDNS, NATO, NATO)

      NSTRT = 1

      DO 10 IC=1, NATOM
       IF(IC .NE. 1)THEN
	NSTRT = NSTRT + NORBAT(IC-1)
       ENDIF
       EDENS(IC) = NUMAT(IC)
C....  EDENS(IC) = 0.D0
      DO 10 NB=NSTRT, NSTRT+NORBAT(IC)-1
       EDENS(IC) = EDENS(IC) - CHDNS(NB,NB)
 10   CONTINUE

      RETURN
      END
