CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS ROUTINE RETURNS THE DENSITY MATRIX, FOR A GIVEN (INCH ALLAH) *C
C* OCCUPIED STATES AND OF COURSE A MATRIX OF THE VARIATIONEL COEFFS. *C
C* WE ALSO CHANGE THE SIGN OF THE COLUMNS OF THE EIGEN MATRIX DU TO  *C
C* THE ESSL ROUTINE.                                                 *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE DENSM(NATO, NOCC, EIGF, PMN)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"

      DIMENSION EIGF(N_ORB,N_ORB), PMN(N_ORB,N_ORB)



C.... NATO : TOTAL NUMBER OF ATOMIC ORBITALS
C.... NOCC : NUMBER OF OCCUPIED STATES
C
      DO 10 MU=1, NATO
      DO 10 NU=1, NATO
       PMN(MU,NU) = 0.D0
       DO 15 I=1, NOCC
	PMN(MU,NU) = PMN(MU,NU) + 2.D0 * EIGF(MU,I) * EIGF(NU,I)
 15    CONTINUE

 10   CONTINUE

      RETURN
      END
