CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS SUBROUTINE RETURNS THE HAMILTONIAN CORE ELECTRONIC ENERGY,   *C
C* WHERE NATO IS THE TOTAL NUMBER OF ATOMIC ORBITALS                 *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE ECORE(NATO, HCORE, PMN, E0)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"

      DIMENSION HCORE(N_ORB,N_ORB), PMN(N_ORB,N_ORB)


      E0 = 0.0D0

      DO 5 MU=1, NATO
      DO 5 NU=1, NATO
       E0 = E0 + PMN(MU,NU) * HCORE(MU,NU)
 5    CONTINUE

      RETURN
      END
