CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS ROUTINE COMPUTES THE FOCK MATRIX, THE DENSITY MATRIX AND OF  *C
C* COURSE THE ENERGY OF THE NTH ITERATION, WHERE NATO IS THE TOTAL   *C
C* NUMBER OF ATOMIC ORBITALS                                         *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE FOCKER(NATO, HCORE, FATIMA, PMN, FOCK)
      IMPLICIT REAL*8 (A-H, O-Z)
      INTEGER SIG
      INCLUDE "../lib95/SIZE.INCL"
      DATA CUTOFF/1.D-12/

      DIMENSION HCORE(N_ORB,N_ORB), FATIMA(*),
     $          PMN(N_ORB,N_ORB), FOCK(N_ORB,N_ORB)


      NSUM = (NATO*(NATO+1))/2

      DO 5 MU=1, NATO
      DO 5 NU=1, NATO
       IP = MAX(MU, NU)
       JP = MIN(MU, NU)
       AUX0  = 0.D0
	     DO 10 LMD=1, NATO
 	     DO 10 SIG=1, NATO
		KP = MAX(LMD, SIG)
		LP = MIN(LMD, SIG)

		IQ = MAX(MU, SIG)
		JQ = MIN(MU, SIG)

		KQ = MAX(LMD, NU)
		LQ = MIN(LMD, NU)

		JRUN1 = ISIND(IP,JP,KP,LP, NATO, NSUM)
		JRUN2 = ISIND(IQ,JQ,KQ,LQ, NATO, NSUM)

		AUX0  = AUX0  + PMN(LMD,SIG) *
     $             (FATIMA(JRUN1) - 0.5D0 * FATIMA(JRUN2))

 10   	CONTINUE

       FOCKMN = HCORE(MU,NU) + AUX0

       if(dabs(fockmn) .le. cutoff)then
	fock(mu, nu) = 0.d0
       else
	fock(mu, nu) = fockmn
       endif
	FOCK(nu, mu) = FOCK(mu, nu)

 5    CONTINUE

      RETURN
      END
