CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C*          THIS SUBROUTINE PRINTS OUT A GIVEN REAL MATRIX.          *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE MATOUT(AMAT, N, M)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"

      DIMENSION AMAT(N_ORB,N_ORB)

      DO 5 I=1, N
       WRITE(*, 1)(AMAT(I,J), J=1, M)
 5    CONTINUE

 1    FORMAT(15(D12.6, 1X))

      DO 10 I=1, N
       WRITE(*, 2)
 10   CONTINUE

 2    FORMAT(13(1H-), $)

      WRITE(*, 3)
 3    FORMAT(//)

      RETURN
      END
