CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS SUBROUTINE COPY A GIVEN 2D MATRIX INTO ANOTHER. IT IS CALLED *C
C* FROM THE ROUTINE SCFCLO                                           *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE SAVEM(AMAT, BMAT, N, M)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"

      DIMENSION AMAT(N_ORB,N_ORB), BMAT(N_ORB,N_ORB)

      DO 5 I=1, N
      DO 5 J=1, M
       BMAT(I,J) = 0.0d0
       BMAT(I,J) = AMAT(I,J)
 5    CONTINUE

      RETURN
      END
