CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS PACKAGE IS THE SCF INVOLVED IN THE STOP PACKAGE. INCH ALLAH  *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE SCFCLO(NATOM,NCHARG,NUMAT,NORBAT,ENC,SOVL,HCORE,HKORE,
     $                                                     FATIMA)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"

      DIMENSION NUMAT(*),NORBAT(*)
      DIMENSION HKORE(N_ORB,N_ORB)
      DIMENSION SOVL(N_ORB,N_ORB), HCORE(N_ORB,N_ORB),
     $          HT((N_ORB*(N_ORB+1))/2)
c     $          HT(NNSM)
       DIMENSION SOVLP(N_ORB,N_ORB),HCORP(N_ORB,N_ORB), EIGV(N_ORB),
     $          EIGF(N_ORB,N_ORB), AUX(2*N_ORB), PMN(N_ORB,N_ORB)

      DIMENSION FOCK(N_ORB,N_ORB), FOCKP(N_ORB,N_ORB)
      DIMENSION EDENS(N_ORB), CHDNS(N_ORB, N_ORB)
      DIMENSION FATIMA(*)

C.... TOTAL NUMBER OF ATOMIC ORBITALS

      NATO = 0

      DO 5 I=1, NATOM
       NATO = NATO + NORBAT(I)
 5    CONTINUE

c.... COMPUTATION OF THE NUMBER OF OCCUPIED STATES FOR A CLOSED SHELL

      NOCC = 0

      DO 10 I=1, NATOM
       NOCC = NOCC + NUMAT(I)
 10   CONTINUE

      NOCC = (NOCC-NCHARG)/2

C.... PRINTING THE OVERLAP MATRIX

      WRITE(*, 1)
 1    FORMAT(/, 14HOVERLAP MATRIX , /, 14(1H-), /)

      CALL MATOUT(SOVL, NATO, NATO)

C.... PRINTING THE CORE MATRIX

      WRITE(*, 2)
 2    FORMAT(/, 11HCORE MATRIX, /, 11(1H-), /)

      CALL MATOUT(HCORE, NATO, NATO)

C.... ***************************************************** ....C

C.... SAVING THE CORE MATRIX INTO THE MATRICES HCORE AND SOVL INTO HCORP AND
C.... SOVLP RESPECTIVELY

      CALL SAVEM(SOVL, SOVLP, NATO, NATO)
      CALL SAVEM(HCORE, HCORP, NATO, NATO)

C.... COMPUTING THE INITIAL GUESS. THE GUESS IS THE SOLUTION OF THE
C.... CORE MATRIX

      CALL DSYGV(1, HCORP,N_ORB, SOVLP,N_ORB, EIGV, EIGF,N_ORB, NATO,
     $                                                   AUX, 2*NATO)
c      call eign(HCORP,EIGV,N_ORB,NATO,1.0d-10,fail)

c      CALL PREJAC(NATO,EIGV,EIGF,HCORP,SOVLP,HT)
 
c      CALL JACOBI(N_ORB,HT,EIGF,EIGV,NATO,NATO,1d-10,10,-1)
	WRITE(*, 3)
 3    FORMAT(12HEIGEN VALUES, /, 12(1H-), /)

	WRITE(*, 4)(EIGV(I), I=1, NATO)
 4    FORMAT(12(D12.6, 1X))
 	WRITE(*, 6)
 6    FORMAT(/, 15HEIGEN FUNCTIONS, /, 15(1H-))
	CALL MATOUT(EIGF, NATO, NATO)
C... COMPUTATION OF THE FIRST DENSITY MATRIX

      CALL DENSM(NATO, NOCC, EIGF, PMN)
	WRITE(*, 7)
 7    FORMAT(/, 24HTHE GUESS DENSITY MATRIX, /, 24(1H-))

	CALL MATOUT(PMN, NATO, NATO)

C.... FIRST APPROXIMATION OF THE TOTAL ENERGY
C.... THE CORE ELECTRONIC ENERGY

      CALL ECORE(NATO, HCORE, PMN, E0)

C.... THE TWO-ELECTRON ENERGY

      CALL TEENER(NATO, FATIMA, PMN, E1)
c      write(*,*)"in scfclo",E0,ENC,E1,E0+ENC
c      STOP
      WRITE(*, 8)E0, ENC+E1, ENC+E0+E1
 8    FORMAT(13HCORE ENERGY :, D16.10, 2X, 18HREPULSION ENERGY :,
     $       D16.10, 2X, 14HTOTAL ENERGY :, D16.10, /, 97(1H-), /)

ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
      CALL CHDENS(NATOM, NATO, NORBAT, NUMAT, SOVL, PMN, EDENS, CHDNS)
c      write(*, *)'ATOMIC CHARGES '
cDGEMM
      CALL VECTOUT(EDENS, NATOM)
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
C.... ************************************************************ ....C

      EN1  = E0 + E1
      EN2  = 0.D0

      EPS  = 1.D-11
      ITER = 0


      DO 15 WHILE(DABS(EN1-EN2) .GT. EPS .AND. ITER .LE. 11)

       EN1 = EN2

       CALL FOCKER(NATO, HCORE, FATIMA, PMN, FOCK)

	WRITE(*, 9)ITER+1
 9     FORMAT(31H FOCK MATRIX OF THE ITERATION :, I3, /, 33(1H-), /)
	CALL MATOUT(FOCK, NATO, NATO)


C.... SAVING THE OVERLAP AND THE FOCK MATRICES

       CALL SAVEM(SOVL, SOVLP, NATO, NATO)
c       CALL SAVEM(FOCK, FOCKP, NATO, NATO)

C.... DIAGONALIZATION OF THE FOCK MATRIX

      CALL DSYGV(1, FOCK, N_ORB, SOVLP,N_ORB, EIGV, EIGF,N_ORB, NATO,
     $                                                    AUX, 2*NATO)
c      CALL PREJAC(NATO,EIGV,EIGF,FOCKP,SOVLP,HT)
c      NIN = NATO
c      CALL JACOBI(N_ORB,HT,EIGF,EIGV,NIN,NIN,1d-10,1,-1)
	WRITE(*, 3)
	CALL VECTOUT(EIGV, NATO)
	WRITE(*, 11)ITER+1
 11   FORMAT(32HEIGEN MATRIX FOR THE ITERATION :, I2, /, 34(1H-), /)
	CALL MATOUT(EIGF, NATO, NATO)

C.... COMPUTATION OF THE NTH DENSITY MATRIX

      CALL DENSM(NATO, NOCC, EIGF, PMN)
c
      CALL ECORE(NATO, HKORE, PMN, EK)
ccc	write(*, *)'DENSITY MATRIX '
ccc	call matout(pmn, nato, nato)

ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
      CALL CHDENS(NATOM, NATO, NORBAT, NUMAT, SOVL, PMN, EDENS, CHDNS)
cDGEMM
cc      write(*, *)'ATOMIC CHARGES '
ccc      CALL VECTOUT(EDENS, NATOM)
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
C.... COMPUTATION OF THE NTH APPROXIMATION THE TWO-ELECTRON ENERGY

       CALL ECORE (NATO, HCORE, PMN, E0)
       CALL TEENER(NATO, FATIMA, PMN, E1)

C.... COMPUTATION OF THE NTH APPROXIMATION OF THE ELECTRONIC ENERGY

       EN2 = E0 + E1
       write(*,*)"kinetic energy",EK
       WRITE(*, 8) E0, ENC+E1, ENC+EN2

C.... INCREMENTING THE ITERATION LIMIT

      ITER = ITER + 1

 15   CONTINUE

	WRITE(*,17)
 17   FORMAT(16HDENSITY MATRIX :, /, 16(1H-), /)
	CALL MATOUT (PMN, NATO, NATO)


C.... ELECTRONIC CHARGE DENSITY ANALYSIS

      CALL CHDENS(NATOM, NATO, NORBAT, NUMAT, SOVL, PMN, EDENS, CHDNS)
cDGEMM
      WRITE(*, 13)
 13   FORMAT(80(1H*), /, 1H*, 78X, 1H*, /, 1H*, 15X,
     $       48HMULLIKEN POPULATION ANALYSIS, ELECTRONIC CHARGES,
     $       15X, 1H*, /, 1H*, 78X, 1H*, / 80(1H*))

      CALL VECTOUT(EDENS, NATOM)

C.... TOTAL NUMBER OF ELECTRON INVOLVED IN THE SYSTEM

C     ZTOT = 0.D0
C     DO 156 I=1, NATO
C     DO 156 J=1, NATO
C      ZTOT = ZTOT + CHDNS(I, J)
C156  CONTINUE

      ZTOT = 0.D0
      DO 156 I=1, NATOM
       ZTOT = ZTOT + EDENS(I)
 156  CONTINUE

      WRITE(*, 14)ZTOT
 14   FORMAT(30HNUMBER OF ELECTRONS INVOLVED :, D16.10, /, 53(1H-), /)

C.... SUMMARY OF THE INFORMATIONS

      WRITE(*, 16)ITER, ENC+EN2, EN2-EN1
 16   FORMAT(25HSCF EXITED AT ITERATION :, I2, 2X, 13HWITH ENERGY :,
     $                                 D16.10, 2X, 10HGRADIENT :, D12.6)

 110  RETURN
      END
