CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C*          THIS SUBROUTINE PRINTS OUT A GIVEN REAL VECTOR.          *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE VECTOUT(VECT, N)
      IMPLICIT REAL*8 (A-H, O-Z)

      DIMENSION VECT(*)

      WRITE(*, 1)(VECT(I), I=1, N)

 1    FORMAT(15(D12.6, 1X))

      DO 5 I=1, N
       WRITE(*, 2)
 5    CONTINUE

 2    FORMAT(13(1H-), $)

      WRITE(*, 3)
 3    FORMAT(//)

      RETURN
      END


