CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS SUBROUTINE COMPUTES THE TWO-CENTER EXCHANGE INTEGRALS USED   *C
C* IN THE SCF PROCEDURE. IT IS CALLED FROM THE ROUTINE TOELEC.       *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE EXCH2(NEPSIL, NTORB,NSUM, LM123, IC1,IC2, NORBAT,
     $                             NLMAT, ZETAAT, ZETAMY, XYZAT, FATIMA)
      IMPLICIT REAL*8 (A-H, O-Z)
      INTEGER ZETST1, ZETST2
      DIMENSION NORBAT(*), NLMAT(*), ZETAAT(*), ZETAMY(*), XYZAT(*),
     $                                                         FATIMA(*)
      DIMENSION XYZV(3)


cccc      WRITE(*, 1)IC1, IC2, IC1, IC2
cccc 1    FORMAT('EXCH2 : ', 4(I2, 2X))

C.... COMPUTATION OF THE COORDINATES OF THE CENTER LABLED IC2, TO WHICH THE
C.... ORBITALS X2(1) AND X4(2) ARE ATTACHED

      NIC1 = 3*(IC1-1)+1
      NIC2 = 3*(IC2-1)+1

      CALL CARTCO(XYZAT(NIC1),XYZAT(NIC2), XYZV, RVMOD,THETRV,PHIRV)

C.... COMPUTATION OF THE STARTING INDICES FOR THE ORBITALS AND THE SLATER
C.... EXPONENTS

      CALL NDXSTR(NORBAT, IC1, NLMST1, ZETST1)
      CALL NDXSTR(NORBAT, IC2, NLMST2, ZETST2)

C.... COMPUTATION OF THE TWO-CENTER EXCHANGE INTEGRALS

      CALL EXCH21(NEPSIL, NTORB,NSUM, LM123, NORBAT(IC1),NORBAT(IC2),
     $     NLMAT(NLMST1),NLMAT(NLMST2), ZETAAT(ZETST1),ZETAAT(ZETST2),
     $                          ZETAMY(IC2), RVMOD,THETRV,PHIRV, FATIMA)

      RETURN
      END
