CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS ROUTINE RETURNS THE RADIAL PART OF THE TWO-CENTER EXCHANGE   *C
C* INTEGRALS.                                                        *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE RADP(L1,L2, N3,L3,M3, N4,L4,M4, ZETA3,ZETA4, AB, ZETAM,
     $                       RLEG01,RLEG02, BESF01, X4NL, RLEAG0, RADAR)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"
      DIMENSION RLEG01(*), RLEG02(*), BESF01(*), X4NL(*), RLEAG0(*),
     $          RADAR(*)
      COMMON/BESHER/HEREX(LTOT6*LMHERM), BESS01(LTOT6*(LDEV+1))
      COMMON/COMG01/GEGIN1(LMHERM*(LDEV+1))
      COMMON/COMV00/VLRAD(LEA05*(LMDMAX+1)*(L1MAX+1)**3)
      COMMON/EXCH01/ZETA3P, N3P, LP4, INDIC, LMD2
      EXTERNAL RAD06, RAD07


C.... PASSAGE TO A COMMON

      ZETA3P = ZETA3
      N3P    = N3

C.... COMPUTATION OF THE GEGENBAUER COEFFICIENTS INVOLVED IN THE OUTER INTEGRAL

      IN = 1
      CALL ABIN02(ZETA4, AB, N4-L4, RLEG01,L1_3, RLEG02,L4_6,
     $                     RLEAG0,IN,LEA05, BESF01, X4NL, HEREX, BESS01)

      INDEX = 1

      DO 5 LMD=0, LMDMAX+L3+L4
       IND1 = 1
      DO 5 I=1, LEA05
       R2   = RLEAG0(I)
       IND2 = LMD+1
       CALL BAD01(IND1, IND2, ZETA4, AB, R2, N4-L4, LMD, XYINT)
       GEGIN1(INDEX) = XYINT
       INDEX         = INDEX + 1
 5    CONTINUE

C.... COMPUTATION OF THE RADIAL PART OF THE TWO-CENTER EXCHANGE INTEGRALS

      INDEX = 1
      INDIC = 0

      DO 10 L=0, LMDMAX
      DO 10 LP2=0, L2
      DO 10 LP12=IABS(L1-LP2), L1+LP2, 2
      DO 10 LMD1=IABS(L-LP12), L+LP12, 2
       INDIC = INDIC + 1
      DO 10 LP4=0, L4
      DO 10 LP34=IABS(L3-LP4), L3+LP4, 2
      DO 10 LMD2=IABS(L-LP34), L+LP34, 2
       XINT1 = DGLNQ(RAD06, 0.D0, AB, LEG07)
       XINT2 = DGLGQ(RAD07, AB, ZETAM, LAG05)
       RADAR(INDEX) = XINT1 + XINT2
       INDEX = INDEX + 1
 10   CONTINUE

      RETURN
      END



CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS ROUTINE RETURNS THE RADIAL PART OF THE TWO-CENTER EXCHANGE   *C
C* INTEGRALS OVER THE RANGE [0, AB].                                 *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE RAD06(T, Y, N)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"
      DIMENSION T(*), Y(*)
      COMMON/COMG01/GEGIN1(LMHERM*(LDEV+1))
      COMMON/COMV00/VLRAD(LEA05*(LMDMAX+1)*(L1MAX+1)**3)
      COMMON/EXCH01/ZETA3, N3, LP4, INDIC, LMD2
      COMMON/R2POW/R2PUIS((L3MAX+L4MAX+3)*LEA05)
      COMMON/R2SQR/R2SQRT(LEA05)
      COMMON/EXPO/SEXP(LEA05*LEA06), SEXP1(LEA05)

      IND1 = (INDIC-1)*LEA05
      IND2 = LMD2*LEA05
      INDX = (N3+LP4)*LEA05

      DO 5 I=1, N
       Y(I) = R2SQRT(I) * R2PUIS(INDX+I) * SEXP1(I) *
     $                                    VLRAD(IND1+I) * GEGIN1(IND2+I)
 5    CONTINUE

      RETURN
      END




CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS ROUTINE RETURNS THE RADIAL PART OF THE TWO-CENTER EXCHANGE   *C
C* INTEGRALS OVER THE RANGE [AB, +\INFINITY[.                        *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE RAD07(T, Y, N)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"
      DIMENSION T(*), Y(*)
      COMMON/COMG01/GEGIN1(LMHERM*(LDEV+1))
      COMMON/COMV00/VLRAD(LEA05*(LMDMAX+1)*(L1MAX+1)**3)
      COMMON/EXCH01/ZETA3, N3, LP4, INDIC, LMD2
      COMMON/R2POW/R2PUIS((L3MAX+L4MAX+3)*LEA05)
      COMMON/R2SQR/R2SQRT(LEA05)
      COMMON/EXPO/SEXP(LEA05*LEA06), SEXP1(LEA05)

      IND1 = (INDIC-1)*LEA05 + LEG07
      IND2 = LMD2*LEA05 + LEG07
      INDX = (N3+LP4)*LEA05 + LEG07

      DO 5 I=1, N
       Y(I) = R2SQRT(LEG07+I) * R2PUIS(INDX+I) * SEXP1(LEG07+I) *
     $                                    VLRAD(IND1+I) * GEGIN1(IND2+I)
 5    CONTINUE

      RETURN
      END

