CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS ROUTINE RETURNS THE COEFFICIENTS INVOLVED IN THE GEGENBAUER  *C
C* ADDITION THEOREM FOR THE THREE-CENTER TWO-ELECTRON INTEGRALS.     *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE GEGEN4(LMDL12, NL, ZETA, AB, RLEG01, RLEG02, RLEAG0,
     $                                              BESF01, X4NL, GEGIN)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"
      DIMENSION RLEG01(*), RLEG02(*), RLEAG0(*),
     $                                      BESF01(*), X4NL(*), GEGIN(*)
      COMMON/BESHER/HEREX(LTOT6*LMHERM), BESS01(LTOT6*(LDEV+1))


C.... COMPUTATION OF THE HERMIT POLYNOMIALS

      IN = 1
      CALL ABIN02(ZETA, AB, NL, RLEG01,L1_3, RLEG02,L4_6,
     $                     RLEAG0,IN,LEA04, BESF01, X4NL, HEREX, BESS01)

      INDEX = 1

      DO 5 LMD=0, LMDL12-1
       IND1 = 1
      DO 5 I=1, LEA04
       R2   = RLEAG0(I)
       IND2 = LMD+1
       CALL BAD01(IND1, IND2, ZETA, AB, R2, NL, LMD, XYINT)
       GEGIN(INDEX) = XYINT
       INDEX        = INDEX + 1
 5    CONTINUE

      RETURN
      END
