CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS ROUTINE RETURNS THE RADIAL INTEGRAL OCCURING IN THE THREE-   *C
C* CENTER COULOMB INTEGRALS. THESE VALUES ARE STORED IN THE ON-      *C
C* DIMENSIONAL ARRAY 'RADAR'.                                        *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE RTCTEI(INDIC, L1,L2,L3,L4, ZETA34, RMIN,RMAX, RADAR)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"
      DIMENSION RADAR(*)
      COMMON/STOP04/L12, L, LP3, LP4, LMD1, LMD2, ISTR, NSTRT
      COMMON/COMG00/GEGIN0(LMHERM*LMHERM*(LMDMAX+L1MAX+L2MAX+1))
      COMMON/COMG01/GEGIN1(LMHERM*(LDEV+1))
      COMMON/COMV00/VL((NORBM*(NORBM+1))/2*(L1MAX+L2MAX+1)*LEA04)
      EXTERNAL RAD05


C.... PASSAGE TO COMMON

      L12   = L1+L2
      NSTRT = INDIC*LEA04*(L1MAX+L2MAX+1)

      INDEX = 1

      DO 5 L=IABS(L1-L2), L1+L2, 2
      DO 5 LP3=0, L3
      DO 5 LP4=0, L4
      DO 5 LP34=IABS(LP3-LP4), LP3+LP4, 2
      DO 5 LP=IABS(L-LP34), L+LP34, 2
      DO 5 LMD1=0, LMDMAX
      DO 5 LMD2=IABS(LP-LMD1), LP+LMD1, 2
       ISTR         = 0
       XINT1        = DGLNQ(RAD05, 0.D0, RMIN, LEG05)
       ISTR         = ISTR + LEG05
       XINT2        = DGLNQ(RAD05, RMIN, RMAX, LEG06)
       ISTR         = ISTR + LEG06
       XINT3        = DGLGQ(RAD05, RMAX, ZETA34, LAG04)
       RADAR(INDEX) = XINT1 + XINT2 + XINT3
       INDEX        = INDEX + 1
 5    CONTINUE

      RETURN
      END


CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS SUBROUTINE IS CALLED FROM THE DGLNQ AND DGLGQ. IT RETURNS THE*C
C* VALUE OF THE RADIAL INVOLVED IN THE THREE-CENTER COULOMB INTEGRLS.*C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE RAD05(T, Y, N)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "../lib95/SIZE.INCL"
      DIMENSION T(*), Y(*)
      COMMON/STOP04/L12, L, LP3, LP4, LMD1, LMD2, ISTR, NSTRT
      COMMON/COMG00/GEGIN0(LMHERM*LMHERM*(LMDMAX+L1MAX+L2MAX+1))
      COMMON/COMG01/GEGIN1(LMHERM*(LDEV+1))
      COMMON/COMV00/VL((NORBM*(NORBM+1))/2*(L1MAX+L2MAX+1)*LEA04)

      INDO1 = LMD1*LEA04 + ISTR
      INDO2 = LMD2*LEA04 + ISTR

      DO 5 I=1, N
       INDX = NSTRT + (ISTR+I-1)*(L12+1) + L+1
       R2   = T(I)
       Y(I) =  R2**(LP3+LP4+1) * VL(INDX) *
     $                                 GEGIN0(INDO1+I) * GEGIN1(INDO2+I)
 5    CONTINUE

      RETURN
      END
