CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS SUBROUTINE COMPUTES THE THREE-CENTER TWO-ELECTRON COULOMB    *C
C* INTEGRALS NEEDED IN THE SCF PROCEDURE. IT IS CALLED FROM TOELEC.  *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE TCTEIS(NEPSIL, NTORB,NSUM, LM123, IC1,IC2,IC3, NORBAT,
     $                           NLMAT, ZETAAT, ZETAMY, XYZAT, FATIMA)
      IMPLICIT REAL*8 (A-H, O-Z)
      INTEGER ZETST1, ZETST2, ZETST3
      INCLUDE "../lib95/CONST.INCL"

      DIMENSION NORBAT(*), NLMAT(*), ZETAAT(*), ZETAMY(*), XYZAT(*),
     $                                                    FATIMA(*)

      DIMENSION XYZV(3)


c     WRITE(*, 1)IC1,IC2,IC3
c1    FORMAT('TRI32 : ', 4(I2, 2X))


C.... COMPUTATION OF THE COORDINATES OF THE CENTER LABELED IC2 TO WHICH THE
C.... ORBITALS X3(2) AND X4(2)

      NIC1 = 3*(IC1-1)+1
      NIC2 = 3*(IC2-1)+1
      NIC3 = 3*(IC3-1)+1

      CALL CARTCO(XYZAT(NIC1),XYZAT(NIC2), XYZV, RB,THETRB,PHIRB)
      CALL CARTCO(XYZAT(NIC1),XYZAT(NIC3), XYZV, RC,THETRC,PHIRC)
C.... COMPUTATION OF THE STARTING INDICES FOR THE ORBITALS AND THE SLATER
C.... EXPONENTS

      CALL NDXSTR(NORBAT, IC1, NLMST1, ZETST1)
      CALL NDXSTR(NORBAT, IC2, NLMST2, ZETST2)
      CALL NDXSTR(NORBAT, IC3, NLMST3, ZETST3)

C.... COMPUTATION OF THE THREE-CENTER TWO-ELECTRON COULOMB INTEGRALS

      CALL TRI32(NEPSIL, NTORB,NSUM, LM123,
     $            NORBAT(IC1),NORBAT(IC2),NORBAT(IC3),
     $             NLMAT(NLMST1),NLMAT(NLMST2),NLMAT(NLMST3),
     $              ZETAAT(ZETST1), ZETAAT(ZETST2), ZETAAT(ZETST3),
     $                     RB,THETRB,PHIRB, RC,THETRC,PHIRC, FATIMA)

      RETURN
      END
