      SUBROUTINE BAD01(INP1, INP2, ZETA2, AB, R, NL, LMD, XYINT)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "SIZE.INCL"
      INCLUDE "CONST.INCL"
      PARAMETER(ZP=4.D0, ZP1=4.D0)
      COMMON/BESHER/HEREX(LTOT6*LMHERM), BESS01(LTOT6*(LDEV+1))
      COMMON/COMBAD/IND1, IND2
      EXTERNAL GLEG3, GLEG4

      IND1 = INP1
      IND2 = INP2

      XINF = 1.D0/3.D0
      XMID = 2.D0/3.D0
      XINT1 = DGLNQ(GLEG3, 0.D0, XINF, L001)
      XINT2 = DGLNQ(GLEG3, XINF, XMID, L002)
      XINT3 = DGLNQ(GLEG3, XMID, 1.D0, L003)
      XINT  = XINT1 + XINT2 + XINT3

      YINT1 = DGLNQ(GLEG4, 0.D0, XINF, L004)
      YINT2 = DGLNQ(GLEG4, XINF, XMID, L005)
      YINT3 = DGLNQ(GLEG4, XMID, 1.D0, L006)
      YINT  = YINT1 + YINT2 + YINT3

      XYINT = ZP * XINT + ZP1 * YINT

      INP1 = IND1
      INP2 = IND2

      RETURN
      END




      SUBROUTINE GLEG3(T, Y, N)
      IMPLICIT REAL*8 (A-H, O-Z)
      DIMENSION T(*), Y(*)
      INCLUDE "CONST.INCL"
      INCLUDE "SIZE.INCL"
      COMMON/BESHER/HEREX(LTOT6*LMHERM), BESS01(LTOT6*(LDEV+1))
      COMMON/COMBAD/IND1, IND2


      LMD1 = LDEV + 1

      DO 5 I=1, N
       Y(I) = HEREX(IND1) * BESS01(IND2)
       IND1 = IND1 + 1
       IND2 = IND2 + LMD1
 5    CONTINUE

      RETURN
      END



      SUBROUTINE GLEG4(T, Y, N)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "CONST.INCL"
      INCLUDE "SIZE.INCL"
      DIMENSION T(*), Y(*)
      COMMON/BESHER/HEREX(LTOT6*LMHERM), BESS01(LTOT6*(LDEV+1))
      COMMON/COMBAD/IND1, IND2

      LMD1 = LDEV + 1

      DO 5 I=1, N
       Y(I) = HEREX(IND1) * BESS01(IND2)
       IND1 = IND1 + 1
       IND2 = IND2 + LMD1
 5    CONTINUE

      RETURN
      END
