      SUBROUTINE CM2REA(NTORB, NLMAT, XCORE, HCORE)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "SIZE.INCL"
      DATA SQRT2/1.41421356237309505D0/

      DIMENSION NLMAT(*), XCORE(N_ORB, N_ORB), HCORE(N_ORB, N_ORB)


      DO 5 LINE=1, NTORB
      DO 5 ICOL=LINE, NTORB

       M1 = NLMAT(5*LINE)
       M2 = NLMAT(5*ICOL)

       DNUM1  = (-1)**M1
       DNUM2  = (-1)**M2
       DNUM12 = DNUM1 * DNUM2

       IF(M1.EQ.0 .AND. M2.EQ.0)THEN
	HCORE(LINE, ICOL) = XCORE(LINE, ICOL)
	HCORE(ICOL, LINE) = HCORE(LINE, ICOL)

       ELSE
	IF(M1.EQ.0 .AND. M2.GT.0)THEN
	 HCORE(LINE, ICOL) = SQRT2 * DNUM2 * XCORE(LINE, ICOL)
	 HCORE(ICOL, LINE) = HCORE(LINE, ICOL)

	 HCORE(LINE, ICOL+1) = SQRT2 * DNUM2 * XCORE(ICOL, LINE)
	 HCORE(ICOL+1, LINE) = HCORE(LINE, ICOL+1)

	ELSE
	 IF(M1.GT.0 .AND. M2.EQ.0)THEN

	  HCORE(LINE, ICOL) = SQRT2 * DNUM1 * XCORE(LINE, ICOL)
	  HCORE(ICOL, LINE) = HCORE(LINE, ICOL)

	  HCORE(LINE+1, ICOL) = -SQRT2 * DNUM1 * XCORE(ICOL, LINE)
	  HCORE(ICOL, LINE+1) = HCORE(LINE+1, ICOL)

	 ELSE
	  IF(M1.GT.0 .AND. M2.GT.0)THEN

	   HCORE(LINE, ICOL) = DNUM12 * XCORE(LINE, ICOL) +
     $                                        DNUM1 * XCORE(LINE,ICOL+1)
	   HCORE(ICOL, LINE) = HCORE(LINE, ICOL)

	   HCORE(LINE+1, ICOL+1) = DNUM12 * XCORE(LINE,ICOL) -
     $                                        DNUM1 * XCORE(LINE,ICOL+1)
	   HCORE(ICOL+1, LINE+1) = HCORE(LINE+1, ICOL+1)

	   IF(LINE .NE. ICOL)THEN
	    HCORE(LINE, ICOL+1) = DNUM12 * XCORE(ICOL,LINE) -
     $                                        DNUM1 * XCORE(ICOL+1,LINE)
	    HCORE(ICOL+1, LINE) = HCORE(LINE, ICOL+1)

	    HCORE(LINE+1, ICOL) = - DNUM12 * XCORE(ICOL,LINE) -
     $                                        DNUM1 * XCORE(ICOL+1,LINE)
	    HCORE(ICOL, LINE+1) = HCORE(LINE+1, ICOL)

	   ELSE
	    HCORE(LINE, ICOL+1) = - DNUM1 * XCORE(ICOL+1, LINE)
	    HCORE(ICOL+1, LINE) = HCORE(LINE, ICOL+1)
	   ENDIF

	  ENDIF
	 ENDIF
	ENDIF
       ENDIF

5     CONTINUE

      RETURN
      END
