C.... COMBINAISON DES INTEGRALES

      SUBROUTINE CMBINT(M1,M2,M3,M4, BOOLI0,BOOLI1,BOOLJ0,BOOLJ1,
     $          BOOLK0,BOOLK1,BOOLL0,BOOLL1, IP,IQ,IR,IS, JP,JQ,JR,JS,
     $             KP,KQ,KR,KS, LP,LQ,LR,LS, IY,JY,KY,LY, IX,JX,KX,LX,
     $                                     NTORB, NSUM, OUIZA, FATIMA)

      IMPLICIT REAL*8 (A-H, O-Z)
      COMPLEX*16 OUIZA
      LOGICAL*1 BOOLI0,BOOLI1,BOOLJ0,BOOLJ1, BOOLK0,BOOLK1,BOOLL0,BOOLL1
      LOGICAL*1 BOOL1,BOOL2,BOOL3,BOOL4,BOOL5,BOOL6

      DIMENSION OUIZA(20,20,20,20), FATIMA(*)


C.... FOURTH CASE : ALL THE ORBITALS ARE IMAGINARY

      IF(BOOLI1 .AND. BOOLJ1 .AND. BOOLK1 .AND. BOOLL1)THEN
       CALL CMINT4(M1,M2,M3,M4, IY,JY,KY,LY, IX,JX,KX,LX,
     $             IP,IQ,IR,IS, JP,JQ,JR,JS, KP,KQ,KR,KS, LP,LQ,LR,LS,
     $                                     NTORB, NSUM, OUIZA, FATIMA)
      ELSE

C.... THIRD CASE : ONLY ONE OF THE FOUR ORBITALS IS REAL

       BOOL1 = BOOLI1 .AND. BOOLJ1 .AND. BOOLK1 .AND. BOOLL0
       BOOL2 = BOOLI1 .AND. BOOLJ1 .AND. BOOLK0 .AND. BOOLL1
       BOOL3 = BOOLI1 .AND. BOOLJ0 .AND. BOOLK1 .AND. BOOLL1
       BOOL4 = BOOLI0 .AND. BOOLJ1 .AND. BOOLK1 .AND. BOOLL1

       IF(BOOL1 .OR. BOOL2 .OR. BOOL3 .OR. BOOL4)THEN

	CALL CMINT3(M1,M2,M3,M4, BOOL1,BOOL2,BOOL3,BOOL4,
     $             IY,JY,KY,LY, IX,JX,KX,LX,
     $           IP,IQ,IR,IS, JP,JQ,JR,JS, KP,KQ,KR,KS, LP,LQ,LR,LS,
     $                                    NTORB, NSUM, OUIZA, FATIMA)
       ELSE

C.... SECOND CASE : TWO OF THE FOUR ORBITALS ARE REAL

	BOOL1 = BOOLI1 .AND. BOOLJ1 .AND. BOOLK0 .AND. BOOLL0
	BOOL2 = BOOLI1 .AND. BOOLJ0 .AND. BOOLK1 .AND. BOOLL0
	BOOL3 = BOOLI1 .AND. BOOLJ0 .AND. BOOLK0 .AND. BOOLL1
	BOOL4 = BOOLI0 .AND. BOOLJ1 .AND. BOOLK1 .AND. BOOLL0
	BOOL5 = BOOLI0 .AND. BOOLJ1 .AND. BOOLK0 .AND. BOOLL1
	BOOL6 = BOOLI0 .AND. BOOLJ0 .AND. BOOLK1 .AND. BOOLL1

	IF(BOOL1.OR.BOOL2.OR.BOOL3.OR.BOOL4.OR.BOOL5.OR.BOOL6)THEN
	 CALL CMINT2(M1,M2,M3,M4,BOOL1,BOOL2,BOOL3,BOOL4,BOOL5,BOOL6,
     $             IY,JY,KY,LY, IX,JX,KX,LX,
     $             IP,IQ,IR,IS, JP,JQ,JR,JS, KP,KQ,KR,KS, LP,LQ,LR,LS,
     $                                     NTORB, NSUM, OUIZA, FATIMA)
	ELSE

C.... FIRST CASE : ONLY ONE ORBITAL IS IMAGINARY

	 BOOL1 = BOOLI0 .AND. BOOLJ0 .AND. BOOLK0 .AND. BOOLL1
	 BOOL2 = BOOLI0 .AND. BOOLJ0 .AND. BOOLK1 .AND. BOOLL0
	 BOOL3 = BOOLI0 .AND. BOOLJ1 .AND. BOOLK0 .AND. BOOLL0
	 BOOL4 = BOOLI1 .AND. BOOLJ0 .AND. BOOLK0 .AND. BOOLL0

	 IF(BOOL1 .OR. BOOL2 .OR. BOOL3 .OR. BOOL4)THEN
	  CALL CMINT1(M1,M2,M3,M4, BOOL1,BOOL2,BOOL3,BOOL4,
     $             IY,JY,KY,LY, IX,JX,KX,LX,
     $             IP,IQ,IR,IS, JP,JQ,JR,JS, KP,KQ,KR,KS, LP,LQ,LR,LS,
     $                                     NTORB, NSUM, OUIZA, FATIMA)
	 ELSE

C.... ZEROTH CASE : ALL THE ORBITALS ARE REAL

	  CALL CMINT0(M1,M2,M3,M4, IY,JY,KY,LY, IP,JP,KP,LP,
     $                                    NTORB, NSUM, OUIZA, FATIMA)

	 ENDIF
	ENDIF
       ENDIF
      ENDIF

      RETURN
      END
