      SUBROUTINE ONELEC(NATOM,NTORB,NEPSIL,LM123,NORBAT,NLMAT,ZETAAT,
     $                             ZETAMY,NUMAT,XYZAT,SOVL,HCORE,HZCORE)
      IMPLICIT REAL*8 (A-H, O-Z)
      INCLUDE "./lib95/SIZE.INCL"

      DIMENSION NORBAT(*),NLMAT(*),ZETAAT(*),ZETAMY(*),NUMAT(*),XYZAT(*)
      DIMENSION SOVL(N_ORB,N_ORB),HCORE(N_ORB,N_ORB),XCORE(N_ORB,N_ORB)
      DIMENSION HZCORE(N_ORB,N_ORB),ZCORE(N_ORB,N_ORB)
      DIMENSION YCORE(N_ORB,N_ORB)
      COMMON/INTEGN/NINT


      CALL RAZ2(HCORE, 1,N_ORB, 1,N_ORB)
      CALL RAZ2(XCORE, 1,N_ORB, 1,N_ORB)
      CALL RAZ2(YCORE, 1,N_ORB, 1,N_ORB)
      CALL RAZ2(SOVL,  1,N_ORB, 1,N_ORB)

      DO 5 IOP=1, NATOM
       IC1 = IOP
       IC2 = IOP

       CALL OCOEIS(IC1,IOP,IC2,NUMAT,NORBAT,NLMAT,ZETAAT,XCORE)

 5    CONTINUE

      DO 10 IOP=1, NATOM
       DO 15 IC1=1, IOP-1
	IC2 = IC1
	CALL TCOEIY(IC1,IOP,IC2,NUMAT,NORBAT,NLMAT,ZETAAT,XYZAT,XCORE)
 15    CONTINUE

       DO 20 IC1=IOP+1, NATOM
	IC2 = IC1
	CALL TCOEIY(IC1,IOP,IC2,NUMAT,NORBAT,NLMAT,ZETAAT,XYZAT,XCORE)
 20    CONTINUE
 10   CONTINUE

      DO 25 IOP=1, NATOM
       IC1 = IOP

       DO 30 IC2=1, IOP-1
	CALL TCOEIZ(LM123,IC1,IOP,IC2,NUMAT,NORBAT,NLMAT,ZETAAT,XYZAT,
     $                                                            XCORE)
 30    CONTINUE

       DO 35 IC2=IOP+1, NATOM
	CALL TCOEIZ(LM123,IC1,IOP,IC2,NUMAT,NORBAT,NLMAT,ZETAAT,XYZAT,
     $                                                            XCORE)
 35    CONTINUE

 25   CONTINUE

      CPIN = MCLOCK()
      NINT = 0
      DO 40 IOP=1, NATOM
       DO 45 IC1=1, IOP-1
	DO 50 IC2=IC1+1, IOP-1
	 CALL TRI31(NEPSIL,LM123,IC1,IOP,IC2,NUMAT,NORBAT,NLMAT,ZETAAT,
     $                                                     XYZAT, XCORE)
 50     CONTINUE

	DO 55 IC2=IOP+1, NATOM
	 CALL TRI31(NEPSIL,LM123,IC1,IOP,IC2,NUMAT,NORBAT,NLMAT,ZETAAT,
     $                                                     XYZAT, XCORE)
 55     CONTINUE
 45    CONTINUE

       DO 60 IC1=IOP+1, NATOM
       DO 60 IC2=IC1+1, NATOM
	CALL TRI31(NEPSIL,LM123,IC1,IOP,IC2,NUMAT,NORBAT,NLMAT,ZETAAT,
     $                                                    XYZAT, XCORE)
 60    CONTINUE
 40   CONTINUE
cc      XCORE = 8.91d0/9.0d0*XCORE

      DO 65 IC1=1, NATOM
      DO 65 IC2=IC1, NATOM
       IF(IC1 .EQ. IC2)THEN
	CALL KINET1(IC1, IC2, NORBAT, NLMAT, ZETAAT, ZCORE)
	CALL KINET1(IC1, IC2, NORBAT, NLMAT, ZETAAT, XCORE)
       ELSE
	CALL KINET2(IC1, IC2, NORBAT,NLMAT,ZETAAT,XYZAT,ZCORE)
	CALL KINET2(IC1, IC2, NORBAT,NLMAT,ZETAAT,XYZAT,XCORE)
       ENDIF
 65   CONTINUE
      CALL CM2REA(NTORB, NLMAT, ZCORE, HZCORE)
      CALL CM2REA(NTORB, NLMAT, XCORE, HCORE)

      DO 70 IC1=1, NATOM
       CALL OCOVLS(IC1, NORBAT,NLMAT,ZETAAT, YCORE)
 70   CONTINUE

      DO 75 IC1=1, NATOM
      DO 75 IC2=IC1+1, NATOM
       CALL OVERLP(LM123,IC1,IC2,NORBAT,NLMAT,ZETAAT,XYZAT,YCORE)
 75   CONTINUE

      CALL CM2REA(NTORB, NLMAT, YCORE, SOVL)

      RETURN
      END

