CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS SUBROUTINE COMPUTES THE THREE-CENTER EXCHANGE INTEGRALS USED *C
C* IN THE SCF PROCEDURE. IT IS CALLED FROM THE ROUTINE TOELEC.       *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE EXCH3(NEPSIL, NTORB,NSUM, LM123, IC1,IC2,IC3, NORBAT,
     $                        NLMAT,ZETAAT, ZETAMY, XYZAT, FATIMA)
      IMPLICIT REAL*8 (A-H, O-Z)
      INTEGER ZETST1, ZETST2, ZETST3

      DIMENSION NORBAT(*), NLMAT(*), ZETAAT(*), ZETAMY(*), XYZAT(*),
     $                                           FATIMA(*)

      DIMENSION XYZV(3)
      DATA RADEG/1.74532925199432958D-2/


cccc      WRITE(*, 1)IC1, IC2, IC3
cccc 1    FORMAT('EXCH3 : ', 4(I2, 2X))


C.... COMPUTATION OF THE COORDINATES OF THE CENTER LABELED IC2 AND IC3 TO
C.... WHICH THE ORBITALS X2(1), X3(2) AND X4(2) ARE ATTACHED

      NIC1 = 3*(IC1-1)+1
      NIC2 = 3*(IC2-1)+1
      NIC3 = 3*(IC3-1)+1

      CALL CARTCO(XYZAT(NIC1),XYZAT(NIC2), XYZV, RB,THETRB,PHIRB)
      CALL CARTCO(XYZAT(NIC1),XYZAT(NIC3), XYZV, RC,THETRC,PHIRC)

C.... COMPUTATION OF THE STARTING INDICES FOR THE ORBITALS AND THE SLATER
C.... EXPONENTS

      CALL NDXSTR(NORBAT, IC1, NLMST1, ZETST1)
      CALL NDXSTR(NORBAT, IC2, NLMST2, ZETST2)
      CALL NDXSTR(NORBAT, IC3, NLMST3, ZETST3)

C.... COMPUTATION OF THE THREE-CENTER EXCHANGE INTEGRALS

      ZETMOY = 0.5D0 * (ZETAMY(IC1) + ZETAMY(IC3))
      zzi = zetmoy*(rb+rc)*0.6d0
      if(dexp(-zzi).lt.1.0d-06)goto 100
      CALL EXCH31(NEPSIL, NTORB,NSUM, LM123,
     $         NORBAT(IC1),NORBAT(IC2),NORBAT(IC3),
     $         NLMAT(NLMST1),NLMAT(NLMST2),NLMAT(NLMST3),
     $    ZETAAT(ZETST1),ZETAAT(ZETST2),ZETAAT(ZETST3),ZETMOY,
     $               RB,THETRB,PHIRB, RC,THETRC,PHIRC, FATIMA)

 100  continue
      RETURN
      END
