CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C* THIS SUBROUTINE COMPUTES A SET OF A THREE-CENTER EXCHANGE INTEG-  *C
C* RALS USING SLATER ORBITALS BASIS.                                 *C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE EXCH31(NEPSIL, NTORB,NSUM, LM123, NORB1,NORB2,NORB3,
     $                      NLMA,NLMB,NLMC, ZETAA,ZETAB,ZETAC,ZETAMY,
     $                         AB,THETAB,PHIAB, AC,THETAC,PHIAC, FATIMA)
      IMPLICIT REAL*8 (A-H, O-Z)
      COMPLEX*16 OUIZA
      INCLUDE "../lib95/SIZE.INCL"
      INCLUDE "../lib95/CONST.INCL"

      DIMENSION NLMA(*),NLMB(*),NLMC(*), ZETAA(*),ZETAB(*),ZETAC(*),
     $                                                         FATIMA(*)
      DIMENSION YLMAB(0:((LDEV+1)*(LDEV+2))/2),
     $          YLMAC(0:((LDEV+1)*(LDEV+1)/2)),
     $                                    RADAR((LMDMAX+1)*(L1MAX+1)**6)
      DIMENSION ARGNT1((L2MAX+1)*(2*L2MAX+1)),
     $          ARGNT2((L1MAX+1)*(L2MAX+1)*(2*L2MAX+1)),
     $          ARGNT3((L4MAX+1)*(2*L2MAX+1)),
     $          ARGNT4((L3MAX+1)*(L4MAX+1)*(2*L4MAX+1)),
     $          ARGNT5(LDEV+1), ARGNT6(LDEV+1)
      DIMENSION INX(7), ARVALR(0:LMDMAX+L1234M), ARVALI(0:LMDMAX+L1234M)

      DIMENSION OUIZA(20,20,20,20)


      COMMON/FACT0/FACT(0:30)
      COMMON/DFACT/DFAC(0:100)
      COMMON/GLE01/RLEG01(L1_3)
      COMMON/GLE02/RLEG02(L4_6)
      COMMON/BESS0/BESF01(2*LTOT6)
      COMMON/X4POW/X4NL(10*LTOT6)
      COMMON/GLAE0/RLEAG0(LMHERM), ISP
      COMMON/XROOTS/ROOTS(LEA07*LEA08), ISQ
      COMMON/COMG00/GEGIN0(LMHERM*LMHERM*(LMDMAX+L1MAX+L2MAX+1))
      COMMON/COMV00/VL(LEA07*(LMDMAX+1)*(L1MAX+1)**3)
      COMMON/INTEGN/NINT


C.... THE RMIN AND THE RMAX

      RMIN = DMIN1(AB, AC)
      RMAX = DMAX1(AB, AC)

C.... COMPUTATION OF THE REQUIRED SPHERICAL HARMONICS

cccc      write(*, *)'thetab, phiab, thetac, phiac '
cccc      write(*, *)thetab/radeg, phiab/radeg, thetac/radeg, phiac/radeg

      CALL YLMV1(THETAB, THETAC, YLMAB, YLMAC)

C.... COLLECTING THE ROOTS OF THE DOUBLE INTEGRAL (I.E. OVER R1 AND R2)

      CALL DUMMY3(ZETAMY, RMIN, RMAX)

C.... COMBINING THE GIVEN SET OF SLATER ORBITALS

      DO 5 NAT2=1, NORB2
       JST   = 5*(NAT2-1)
       NO2   = NLMB(JST+2)
       N2    = NLMB(JST+3)
       L2    = NLMB(JST+4)
       M2    = NLMB(JST+5)
       ZETA2 = ZETAB(NAT2)

C.... COMPUTATION OF SOME RADIAL INTEGRALS INVOLVED IN THE T.C.C.D.P

      LMDL12 = LMDMAX+LM123+L2+1
      CALL GEGEN6(LMDL12, N2-L2, ZETA2, AB, RLEG01, RLEG02, RLEAG0,
     $                                      BESF01, ROOTS, X4NL, GEGIN0)

      DO 5 NAT1=1, NORB1
       IST   = 5*(NAT1-1)
       NO1   = NLMA(IST+2)
       N1    = NLMA(IST+3)
       L1    = NLMA(IST+4)
       M1    = NLMA(IST+5)
       ZETA1 = ZETAA(NAT1)

C.... COMPUTATION OF THE TWO-CENTER CHARGE DISTRIBUTION POTENTIAL

      CALL TCCDP2(LM123, N1,L1, N2,L2, ZETA1,ZETA2, AB,RMIN,RMAX,
     $                      RLEG01, RLEG02, BESF01, X4NL, RLEAG0, VL)

C.... COMBINING THE ORBITALS LABELED (3) & (4) TO EVALUATE THE WHOLE INTEGRAL.

      DO 5 NAT4=1, NORB3
       KST   = 5*(NAT4-1)
       NO4   = NLMC(KST+2)
       N4    = NLMC(KST+3)
       L4    = NLMC(KST+4)
       M4    = NLMC(KST+5)
       ZETA4 = ZETAC(NAT4)

      DO 5 NAT3=1, NORB1
       LST   = 5*(NAT3-1)
       NO3   = NLMA(LST+2)
       N3    = NLMA(LST+3)
       L3    = NLMA(LST+4)
       M3    = NLMA(LST+5)
       ZETA3 = ZETAA(NAT3)

C.... COMPUTATION OF THE COEFFICIENTS INVOLVED IN THE SOLID SPHERICAL
C.... HARMONICS ADDITION AND MULTIPLICATION THEOREMS.

       CALL FUSED(DFAC, L1,M1, L2,M2, AB,YLMAB, ARGNT1, ARGNT2)
       CALL FUSED(DFAC, L3,M3, L4,M4, AC,YLMAC, ARGNT3, ARGNT4)

C.... COMPUTATION OF THE PART INVOLVED IN THE TWO-CENTER EXCHANGE INTEGRALS

       CALL RADP1(L1,L2, N3,L3, N4,L4, ZETA3,ZETA4, ZETAMY,
     $         AC,RMIN,RMAX, RLEG01,RLEG02, BESF01, X4NL, RLEAG0, RADAR)


C.... THE NORMALIZATION CONSTANTS

      A12 = ANP(ZETA1,ZETA2,N1,N2)
      A34 = ANP(ZETA3,ZETA4,N3,N4)
c       A1 = (2.d0*ZETA1)**N1 * DSQRT((2.D0*ZETA1)/FACT(2*N1))
c       A2 = (2.d0*ZETA2)**N2 * DSQRT((2.D0*ZETA2)/FACT(2*N2))
c       A3 = (2.d0*ZETA3)**N3 * DSQRT((2.D0*ZETA3)/FACT(2*N3))
c       A4 = (2.d0*ZETA4)**N4 * DSQRT((2.D0*ZETA4)/FACT(2*N4))
      AP1 = A12*A34

c       CSTE =  DFAC(L3)*DFAC(L4) * AP1*
c       A1 = (2.d0*ZETA1)**N1 * DSQRT((2.D0*ZETA1)/FACT(2*N1))
c       A2 = (2.d0*ZETA2)**N2 * DSQRT((2.D0*ZETA2)/FACT(2*N2))
c       A3 = (2.d0*ZETA3)**N3 * DSQRT((2.D0*ZETA3)/FACT(2*N3))
c       A4 = (2.d0*ZETA4)**N4 * DSQRT((2.D0*ZETA4)/FACT(2*N4))

c       CSTE = (-1)**M1 * DFAC(L2)*DFAC(L4) * A1*A2*A3*A4 *
       CSTE = (-1)**M1 * DFAC(L2)*DFAC(L4) * AP1 *
     $        (-AB)**L2 * (-AC)**L4

C.... INIALIZATION OF THE WORKING ARRAY
c       write(*,*)"exch3",l1234m,l3+l4
c       L1234M = L3 + L4
       CALL RAZ0(ARVALR, 0, LMDMAX+L1234M)
       CALL RAZ0(ARVALI, 0, LMDMAX+L1234M)

C.... INITIALIZATION OF THE INDEXING ARRAY

       CALL RAZ1(INX, 1, 7)

C.... COMPUTATION OF THE THREE-CENTER EXCHANGE INTEGRALS
       EXCH3R = 0.0d0
       DO 10 L=0, LMDMAX
	INX(1) = INX(1)+INX(2)+INX(3)+INX(4)+INX(5)+INX(6)+INX(7)
	AUX1   = 1.D0/DBLE(L+L+1)
       DO 10 M=-L, L
	ANGLE  = (M2-M1-M)*PHIAB + (M4-M3+M)*PHIAC
	COSINE = DCOS(ANGLE)
	SINE   = DSIN(ANGLE)
	CALL RAZ1(INX, 2, 7)
	K1 = 0
	K2 = 0
       DO 10 LP2=0, L2
	INX(2) = INX(2)+INX(3)+INX(4)+INX(5)+INX(6)+INX(7)
       DO 10 MP2=MAX(-LP2, -L2+LP2+M2), MIN(LP2, L2-LP2+M2)
	K1   = K1 + 1
	AUX2 = (-1)**MP2 * ARGNT1(K1)
	CALL RAZ1(INX, 3, 7)
       DO 10 LP12=IABS(L1-LP2), L1+LP2, 2
	K2 = K2 + 1
	AUX3 = ARGNT2(K2)
	INX(3) = INX(3)+INX(4)+INX(5)+INX(6)+INX(7)
	CALL RAZ1(INX, 4, 7)
	IF(AUX3 .NE. 0.D0)THEN
	 CALL GAUNT(LP12, MP2-M1, L, M, LMIN, LMAX, M12, NGAUNT, ARGNT5)
	ENDIF
	KO1 = 0
       DO 10 LMD1=IABS(L-LP12), L+LP12, 2
	IF(LMD1 .GE. LMIN)THEN
	 KO1  = KO1 + 1
	 NYL1 = (LMD1*(LMD1+1))/2 + IABS((MP2-M1)-M)
	 MUPW = ((MP2-M1)-M - IABS((MP2-M1)-M))/2
	 AUX4 = (-1)**MUPW * ARGNT5(KO1) * YLMAB(NYL1)
	ELSE
	 AUX4 = 0.D0
	ENDIF
	INX(4) = INX(4)+INX(5)+INX(6)+INX(7)
	CALL RAZ1(INX, 5, 7)

	K3 = 0
	K4 = 0

       DO 10 LP4=0, L4
	INX(5) = INX(5) + INX(6) + INX(7)
       DO 10 MP4=MAX(-LP4, -L4+LP4+M4), MIN(LP4, L4-LP4+M4)
	K3   = K3 + 1
	AUX5 = ARGNT3(K3)
	CALL RAZ1(INX, 6, 7)
       DO 10 LP34=IABS(L3-LP4), L3+LP4, 2
	K4     = K4 + 1
	AUX6   = ARGNT4(K4)
	INX(6) = INX(6) + INX(7)
	CALL RAZ1(INX, 7, 7)
	IF(AUX6 .NE. 0.D0)THEN
	 CALL GAUNT(L, M, LP34, M3-MP4, LMIN1,LMAX1,MP12, NGAUNT,ARGNT6)
	ENDIF
	KO2 = 0
       DO 10 LMD2=IABS(L-LP34), L+LP34, 2
	INX(7) = INX(7) + 1
	INDIC  = INX(1)+INX(2)+INX(3)+INX(4)+INX(5)+INX(6)+INX(7)
	IF(LMD2 .GE. LMIN1)THEN
	 NYL2 = (LMD2*(LMD2+1))/2 + IABS(M+(MP4-M3))
	 KO2  = KO2 + 1
	 MUPW = (M+(MP4-M3) - IABS(M+(MP4-M3)))/2
	 AUX7 = (-1)**MUPW * ARGNT6(KO2) * YLMAC(NYL2)
	ELSE
	 AUX7 = 0.D0
	ENDIF

	ARVALR(L) = ARVALR(L) + AUX1*AUX2*AUX3*AUX4*AUX5*AUX6*
     $                                      AUX7 * COSINE * RADAR(INDIC)

	ARVALI(L) = ARVALI(L) + AUX1*AUX2*AUX3*AUX4*AUX5*AUX6*
     $                                        AUX7 * SINE * RADAR(INDIC)
 10    CONTINUE
c         EXCH3R = EXCH3R + CSTE/DSQRT(AB*AC)*ARVALR(L)
c 15    CONTINUE
c       C3 = 1024.D0*PI5
       LIMI = LMDMAX + L3 + L4
c       LIMI = LMDMAX
       CALL ACCEL(NEPSIL,ARVALR,LIMI,C3*CSTE/DSQRT(AB*AC),EXCH3R)
       CALL ACCEL(NEPSIL,ARVALI,LIMI,C3*CSTE/DSQRT(AB*AC), EXCH3I)
chcn        EXCH3R = C3 *EXCH3R/6.d0
c        EXCH3R = C3 *EXCH3R
c wat       EXCH3R = C3 *EXCH3R/2.22d0
c       WRITE(*, 1)NO1,NO2,NO3,NO4, EXCH3R, EXCH3I
c       write(*,*)"exch 3"

       OUIZA(NAT1,NAT2, NAT3,NAT4) = DCMPLX(EXCH3R, EXCH3I)

       NINT = NINT + 1

 5    CONTINUE


 1    FORMAT(4Z2, 2X, D16.10, 2X, D16.10)

      CALL REAL06(NORB1,NORB2,NORB3, NLMA,NLMB,NLMC,
     $                                       NTORB, NSUM, OUIZA, FATIMA)

      RETURN
      END
